import Sidebar from "@/components/sidebar";
import RightSidebar from "@/components/sidebar/RightSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <div className="w-[100vw]">
      <div className="flex justify-center  max-h-[100vh] overflow-y-clip w-full">
        <div className="flex xl:max-w-[1536px] justify-center w-full  max-h-[100vh]  relative ">
          <div className=" left-0 top-0 static hidden md:block">
            <Sidebar />
          </div>
          <div className='bg-[#FAFAFA] w-[100%] xl:w-[calc(100vw-600px)]  2xl:max-w-[700px]   text-black'>
            <div className=''>
              {children}
            </div>
          </div>
          <div className="hidden  xl:block ">
            <RightSidebar />
          </div>
        </div>
      </div>
    </div>
  );
}
