import Sidebar from "@/components/sidebar";
import RightSidebar from "@/components/sidebar/RightSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className="h-[100vh]">
      <body className="flex bg-[#FAFAFA]">
        <div className="fixed left-0 top-0">
          <Sidebar />
        </div>
        <div className='bg-[#FAFAFA] w-[100%] px-[300px]  text-black'>
          <div className='-200 px-4 pt-6'>
            {children}
          </div>
        </div>
        <div className="fixed right-0 top-0">
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}
